
import React, { useState } from "react";
import { z } from "zod";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { Star } from "lucide-react";
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { toast } from "sonner";
import { Review } from "@/data/products";
import { useUser } from "@clerk/clerk-react";
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar";

const reviewSchema = z.object({
  title: z.string().min(3, { message: "Title must be at least 3 characters" }).max(100),
  comment: z.string().min(10, { message: "Review must be at least 10 characters" }).max(1000),
  recommended: z.boolean().default(false),
  rating: z.number().min(1, { message: "Please select a rating" }).max(5),
});

type ReviewFormValues = z.infer<typeof reviewSchema>;

interface ReviewFormProps {
  productId: string;
  onReviewSubmitted: (review: Review) => void;
  onCancel: () => void;
}

const ReviewForm: React.FC<ReviewFormProps> = ({ productId, onReviewSubmitted, onCancel }) => {
  const [hoveredRating, setHoveredRating] = useState(0);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const { user, isSignedIn } = useUser();
  
  const form = useForm<ReviewFormValues>({
    resolver: zodResolver(reviewSchema),
    defaultValues: {
      title: "",
      comment: "",
      recommended: false,
      rating: 0,
    },
  });

  const selectedRating = form.watch("rating");

  const onSubmit = async (data: ReviewFormValues) => {
    setIsSubmitting(true);
    
    const newReview: Review = {
      id: `r${Date.now()}`, // This ID will be generated by Supabase
      productId,
      userName: isSignedIn ? user?.fullName || `${user?.firstName || ''} ${user?.lastName || ''}`.trim() : "Anonymous User",
      userImage: isSignedIn ? user?.imageUrl : null,
      rating: data.rating,
      date: new Date().toISOString().split('T')[0],
      title: data.title,
      comment: data.comment,
      recommended: data.recommended,
      verified: isSignedIn,
    };
    
    try {
      onReviewSubmitted(newReview);
      
      toast.success("Review submitted successfully", {
        description: "Thank you for your feedback!",
      });
    } catch (error) {
      console.error("Error submitting review:", error);
      toast.error("Failed to submit review", {
        description: "Please try again later.",
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  const renderStar = (rating: number) => {
    const isSelected = selectedRating >= rating;
    const isHovered = hoveredRating >= rating;
    
    return (
      <Star
        key={rating}
        size={24}
        className={`cursor-pointer transition-colors ${
          isSelected || isHovered ? "text-yellow-400 fill-yellow-400" : "text-gray-300"
        }`}
        onClick={() => form.setValue("rating", rating, { shouldValidate: true })}
        onMouseEnter={() => setHoveredRating(rating)}
        onMouseLeave={() => setHoveredRating(0)}
      />
    );
  };

  return (
    <div className="bg-white p-6 rounded-lg border">
      <h3 className="text-xl font-semibold mb-4">Write a Review</h3>
      
      {isSignedIn && (
        <div className="flex items-center mb-4 p-3 bg-gray-50 rounded-lg">
          <Avatar className="h-10 w-10 mr-3">
            <AvatarImage src={user?.imageUrl} alt={user?.fullName || user?.firstName || ""} />
            <AvatarFallback>{user?.firstName?.charAt(0) || "U"}</AvatarFallback>
          </Avatar>
          <div>
            <p className="font-medium">{user?.fullName || `${user?.firstName || ''} ${user?.lastName || ''}`.trim()}</p>
            <p className="text-xs text-gray-500">Your review will be posted with your profile details</p>
          </div>
        </div>
      )}
      
      <Form {...form}>
        <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
          <FormField
            control={form.control}
            name="rating"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Rating</FormLabel>
                <FormControl>
                  <div className="flex">
                    {[1, 2, 3, 4, 5].map(renderStar)}
                  </div>
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />
          
          <FormField
            control={form.control}
            name="title"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Review Title</FormLabel>
                <FormControl>
                  <Input placeholder="Summarize your experience" {...field} />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />
          
          <FormField
            control={form.control}
            name="comment"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Your Review</FormLabel>
                <FormControl>
                  <Textarea 
                    placeholder="What did you like or dislike? How was your experience with this product?" 
                    className="min-h-[120px]"
                    {...field} 
                  />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />
          
          <FormField
            control={form.control}
            name="recommended"
            render={({ field }) => (
              <FormItem className="flex flex-row items-start space-x-3 space-y-0 py-2">
                <FormControl>
                  <Checkbox
                    checked={field.value}
                    onCheckedChange={field.onChange}
                  />
                </FormControl>
                <div className="space-y-1 leading-none">
                  <FormLabel>I recommend this product</FormLabel>
                </div>
              </FormItem>
            )}
          />
          
          <div className="flex justify-end space-x-2 pt-2">
            <Button type="button" variant="outline" onClick={onCancel} disabled={isSubmitting}>Cancel</Button>
            <Button type="submit" disabled={isSubmitting}>
              {isSubmitting ? "Submitting..." : "Submit Review"}
            </Button>
          </div>
        </form>
      </Form>
    </div>
  );
};

export default ReviewForm;
